### ISSUE TITLE
cannot serialize algolia search response after enabling personalization from dashboard or when setting enablepersonalization field to true in search query

### ISSUE THREAD

**Issue by phm1015** [algolia/algoliasearch-client-kotlin#185]
kotlinx.serialization.json.JsonDecodingException: Unexpected JSON token at offset -1: JSON encountered unknown key: 'personalization'. You can enable 'JsonConfiguration.ignoreUnknownKeys' property to ignore unknown keys.
     JSON input: .....alization":{"score":108,"rankingScore":20,"filtersScore":0}}
        at kotlinx.serialization.json.JsonExceptionsKt.UnknownKeyException(JsonExceptions.kt:40)
        at kotlinx.serialization.json.internal.JsonTreeInput.endStructure(TreeJsonInput.kt:160)
        at com.algolia.search.model.search.RankingInfo$$serializer.deserialize(RankingInfo.kt)
        at com.algolia.search.model.search.RankingInfo$$serializer.deserialize(RankingInfo.kt:26)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
        at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
        at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
        at kotlinx.serialization.json.internal.TreeJsonInputKt.readJson(TreeJsonInput.kt:21)
        at kotlinx.serialization.json.Json.fromJson(Json.kt:151)
        at com.algolia.search.model.response.ResponseSearch$Hit.<init>(ResponseSearch.kt:335)
        at com.algolia.search.model.response.ResponseSearch$Hit$Companion.deserialize(ResponseSearch.kt:372)
        at com.algolia.search.model.response.ResponseSearch$Hit$Companion.deserialize(ResponseSearch.kt:369)

**Comment by Aallam** [comment]
Hello @phm1015  -  new beta version 1.4.0-beta03 has been released, it should fix this issue, please try it!

**Comment by phm1015** [comment]
ok thanks
