### ISSUE TITLE
facing issue sending algolia insight events 

### ISSUE THREAD

**Issue by phm1015** [algolia/algoliasearch-client-kotlin#189]
I am trying to send click and conversion events to algolia for personalization
I am using "convertedObjectIDsAfterSearch" and "clickedObjectIDsAfterSearch" methods for  sending events to algolia.

But its causing problems in device having android version 5 and 6.

below is error details

Process: com.example.myapplication, PID: 7659
    java.lang.VerifyError: Rejecting class com.algolia.search.model.insights.InsightsEvent$Companion because it failed compile-time verification (declaration of 'com.algolia.search.model.insights.InsightsEvent$Companion' appears in /data/app/com.example.myapplication-1/base.apk)
        at com.algolia.search.model.insights.InsightsEvent.<clinit>(InsightsEvent.kt)
        at com.algolia.search.endpoint.EndpointInsightsUserImpl.clickedObjectIDsAfterSearch(EndpointInsightsUserImpl.kt:94)
        at com.algolia.search.client.ClientInsights$User.clickedObjectIDsAfterSearch(ClientInsights.kt)
        at com.algolia.search.endpoint.EndpointInsightsUser$DefaultImpls.clickedObjectIDsAfterSearch$default(EndpointInsightsUser.kt:97)
        at com.example.myapplication.MainActivity$searchItemClickEvent$2.invokeSuspend(MainActivity.kt:51)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Aallam** [comment]
Hello @phm1015,
Thank you for reporting the issue. The compiler seems to generate some code that is not compatible with older Android JVMs. We are working on a fix to resolve this issue.

**Comment by phm1015** [comment]
@Aallam  also one more thing to add 
this works fine in android 4.2.2 version(api 19)

hope this might help

**Comment by Aallam** [comment]
@phm1015 - please try the new beta version 1.4.0-beta04, it should fix this issue.

**Comment by phm1015** [comment]
> @phm1015 - please try the new beta version 1.4.0-beta04, it should fix this issue.

@Aallam thanks for feedback

**Comment by phm1015** [comment]
Was there any specific reason why it was working in android 4.2.2 and not android 5?

**Comment by Aallam** [comment]
> Was there any specific reason why it was working in android 4.2.2 and not android 5?

Android runtime has changed between these two versions: Dalvik for Android 4.4 and below and ART for later versions

**Comment by phm1015** [comment]
OK but it was causing problems in 5 and 6 mostly and was working fine in later versions like android 8 ,9 etc.

**Comment by Aallam** [comment]
> OK but it was causing problems in 5 and 6 mostly and was working fine in later versions like android 8 ,9 etc.

The bug seem in the early versions of ART

**Comment by phm1015** [comment]
> > OK but it was causing problems in 5 and 6 mostly and was working fine in later versions like android 8 ,9 etc.
> 
> The bug seems in the early versions of ART

@Aallam thanks for the detailed update
