### ISSUE TITLE
Android Proguard issues with v1.5.1

### ISSUE THREAD

**Issue by vn01971** [algolia/algoliasearch-client-kotlin#231]
We have an android project with `minifyEnabled true` and are using the following proguard rules:
```
-keep,includedescriptorclasses class com.algolia.search.model.**$$serializer { *; }
-keepclassmembers class com.algolia.search.model.** {
    *** Companion;
}
-keepclasseswithmembers class com.algolia.search.model.** {
    kotlinx.serialization.KSerializer serializer(...);
}
```
After upgrading from `com.algolia:instantsearch-android:2.3.1` (which uses v1.3.1 of the client) to `com.algolia:instantsearch-android:2.7.1` (which uses v1.5.1 of the client) we started getting the error shown below. Are there any additional proguard rules we should add?

Note that we used to use this proguard rule, but it also doesn't work.
```
-keep class com.algolia.search.model.** { *; }
```

```
Non-fatal Exception: java.lang.NoClassDefFoundError: n.c.l.r
       at kotlinx.serialization.json.JsonElementSerializer.serialize(JsonElementSerializer.java:45)
       at kotlinx.serialization.json.JsonElementSerializer.serialize(JsonElementSerializer.java:30)
       at kotlinx.serialization.json.internal.PolymorphicKt.encodePolymorphically(PolymorphicKt.java:16)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.java:223)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeJsonElement(StreamingJsonEncoder.java:41)
       at com.algolia.search.model.internal.request.RequestMultipleQueries$Companion.serialize(RequestMultipleQueries.java:49)
       at com.algolia.search.model.internal.request.RequestMultipleQueries$Companion.deserialize(RequestMultipleQueries.java:30)
       at kotlinx.serialization.json.internal.PolymorphicKt.encodePolymorphically(PolymorphicKt.java:16)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.java:223)
       at kotlinx.serialization.json.Json.encodeToString(Json.java:73)
       at com.algolia.search.serialize.internal.JsonKt.toBody(JsonKt.java:77)
       at com.algolia.search.endpoint.internal.EndpointMultipleIndexImpl.multipleQueries(EndpointMultipleIndexImpl.java:46)
       at com.algolia.search.endpoint.internal.EndpointSearchImpl.browse(EndpointSearchImpl.java:67)
       at com.algolia.search.endpoint.EndpointMultipleIndex$DefaultImpls.multipleQueries$default(EndpointMultipleIndex.java:67)
       at com.algolia.search.endpoint.internal.EndpointSearchImpl.advancedSearch(EndpointSearchImpl.java:137)
       at com.algolia.search.client.internal.IndexImpl.advancedSearch(IndexImpl.java:2)
       at com.algolia.instantsearch.helper.searcher.SearcherSingleIndex.search(SearcherSingleIndex.java:58)
       at com.algolia.instantsearch.helper.android.list.SearcherSingleIndexDataSource$loadInitial$1.invokeSuspend(SearcherSingleIndexDataSource.java:35)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoopImplBase.java:274)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:84)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__BuildersKt.java:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__BuildersKt.java:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(BuildersKt.java:1)
       at com.algolia.instantsearch.helper.android.list.SearcherSingleIndexDataSource.loadInitial(SearcherSingleIndexDataSource.java:33)
       at androidx.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:339)
       at androidx.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:175)
       at androidx.paging.PagedList.create(PagedList.java:216)
       at androidx.paging.PagedList$Builder.build(PagedList.java:388)
       at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
       at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
       at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.ExceptionInInitializerError
       at kotlinx.serialization.json.JsonObjectSerializer.<clinit>(JsonObjectSerializer.java:153)
       at kotlinx.serialization.json.JsonElementSerializer.serialize(JsonElementSerializer.java:45)
       at kotlinx.serialization.json.JsonElementSerializer.serialize(JsonElementSerializer.java:30)
       at kotlinx.serialization.json.internal.PolymorphicKt.encodePolymorphically(PolymorphicKt.java:16)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.java:223)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeJsonElement(StreamingJsonEncoder.java:41)
       at com.algolia.search.model.internal.request.RequestMultipleQueries$Companion.serialize(RequestMultipleQueries.java:49)
       at com.algolia.search.model.internal.request.RequestMultipleQueries$Companion.deserialize(RequestMultipleQueries.java:30)
       at kotlinx.serialization.json.internal.PolymorphicKt.encodePolymorphically(PolymorphicKt.java:16)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.java:223)
       at kotlinx.serialization.json.Json.encodeToString(Json.java:73)
       at com.algolia.search.serialize.internal.JsonKt.toBody(JsonKt.java:77)
       at com.algolia.search.endpoint.internal.EndpointMultipleIndexImpl.multipleQueries(EndpointMultipleIndexImpl.java:46)
       at com.algolia.search.endpoint.internal.EndpointSearchImpl.browse(EndpointSearchImpl.java:67)
       at com.algolia.search.endpoint.EndpointMultipleIndex$DefaultImpls.multipleQueries$default(EndpointMultipleIndex.java:67)
       at com.algolia.search.endpoint.internal.EndpointSearchImpl.advancedSearch(EndpointSearchImpl.java:137)
       at com.algolia.search.client.internal.IndexImpl.advancedSearch(IndexImpl.java:2)
       at com.algolia.instantsearch.helper.searcher.SearcherSingleIndex.search(SearcherSingleIndex.java:58)
       at com.algolia.instantsearch.helper.android.list.SearcherSingleIndexDataSource$loadInitial$1.invokeSuspend(SearcherSingleIndexDataSource.java:35)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoopImplBase.java:274)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:84)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__BuildersKt.java:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__BuildersKt.java:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(BuildersKt.java:1)
       at com.algolia.instantsearch.helper.android.list.SearcherSingleIndexDataSource.loadInitial(SearcherSingleIndexDataSource.java:33)
       at androidx.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:339)
       at androidx.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:175)
       at androidx.paging.PagedList.create(PagedList.java:216)
       at androidx.paging.PagedList$Builder.build(PagedList.java:388)
       at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
       at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
       at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by kotlinx.serialization.SerializationException: Serializer for class 'g' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
       at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform_commonKt.java:104)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(SerializersKt__SerializersKt.java:29)
       at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(PlatformKt.java:29)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(SerializersKt__SerializersKt.java:56)
       at kotlinx.serialization.SerializersKt.serializer(SerializersKt.java:1)
       at kotlinx.serialization.SerializersKt__SerializersKt.builtinSerializerOrNull$SerializersKt__SerializersKt(SerializersKt__SerializersKt.java:76)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializerByKTypeImpl$SerializersKt__SerializersKt(SerializersKt__SerializersKt.java:66)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(SerializersKt__SerializersKt.java:38)
       at kotlinx.serialization.SerializersKt.serializer(SerializersKt.java:1)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(SerializersKt__SerializersKt.java:21)
       at kotlinx.serialization.json.JsonObjectSerializer$JsonObjectDescriptor.<init>(JsonObjectSerializer.java:237)
       at kotlinx.serialization.json.JsonObjectSerializer$JsonObjectDescriptor.<clinit>(JsonObjectSerializer.java:148)
       at kotlinx.serialization.json.JsonObjectSerializer.<clinit>(JsonObjectSerializer.java:153)
       at kotlinx.serialization.json.JsonElementSerializer.serialize(JsonElementSerializer.java:45)
       at kotlinx.serialization.json.JsonElementSerializer.serialize(JsonElementSerializer.java:30)
       at kotlinx.serialization.json.internal.PolymorphicKt.encodePolymorphically(PolymorphicKt.java:16)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.java:223)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeJsonElement(StreamingJsonEncoder.java:41)
       at com.algolia.search.model.internal.request.RequestMultipleQueries$Companion.serialize(RequestMultipleQueries.java:49)
       at com.algolia.search.model.internal.request.RequestMultipleQueries$Companion.deserialize(RequestMultipleQueries.java:30)
       at kotlinx.serialization.json.internal.PolymorphicKt.encodePolymorphically(PolymorphicKt.java:16)
       at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.java:223)
       at kotlinx.serialization.json.Json.encodeToString(Json.java:73)
       at com.algolia.search.serialize.internal.JsonKt.toBody(JsonKt.java:77)
       at com.algolia.search.endpoint.internal.EndpointMultipleIndexImpl.multipleQueries(EndpointMultipleIndexImpl.java:46)
       at com.algolia.search.endpoint.internal.EndpointSearchImpl.browse(EndpointSearchImpl.java:67)
       at com.algolia.search.endpoint.EndpointMultipleIndex$DefaultImpls.multipleQueries$default(EndpointMultipleIndex.java:67)
       at com.algolia.search.endpoint.internal.EndpointSearchImpl.advancedSearch(EndpointSearchImpl.java:137)
       at com.algolia.search.client.internal.IndexImpl.advancedSearch(IndexImpl.java:2)
       at com.algolia.instantsearch.helper.searcher.SearcherSingleIndex.search(SearcherSingleIndex.java:58)
       at com.algolia.instantsearch.helper.android.list.SearcherSingleIndexDataSource$loadInitial$1.invokeSuspend(SearcherSingleIndexDataSource.java:35)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoopImplBase.java:274)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:84)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__BuildersKt.java:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__BuildersKt.java:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(BuildersKt.java:1)
       at com.algolia.instantsearch.helper.android.list.SearcherSingleIndexDataSource.loadInitial(SearcherSingleIndexDataSource.java:33)
       at androidx.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:339)
       at androidx.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:175)
       at androidx.paging.PagedList.create(PagedList.java:216)
       at androidx.paging.PagedList$Builder.build(PagedList.java:388)
       at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
       at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
       at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by vn01971** [comment]
I found some rules in the [kotlinx serialization repo](https://github.com/Kotlin/kotlinx.serialization#android) that resolved the issue. These should probably be added to [algoliasearch.pro](https://github.com/algolia/algoliasearch-client-kotlin/blob/develop/src/jvmMain/resources/META-INF/proguard/algoliasearch.pro).
```
# kotlinx-serialization-json specific. Add this if you have java.lang.NoClassDefFoundError kotlinx.serialization.json.JsonObjectSerializer
-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}
```
The other proguard rules I listed in my previous comment weren't necessary since they're already included in algoliasearch.pro and we're using R8 (as described in this repo's readme).

**Comment by Aallam** [comment]
Hi @vn01971, thank you for reporting this! We will look into adding the missing rules.

**Comment by b95505017** [comment]
But I think this rule should apply by kotlinx-serialization instead of attached in Algolia library.
