### ISSUE TITLE
Failed to parse _highlightResult

### ISSUE THREAD

**Issue by lenoch0d** [algolia/algoliasearch-client-kotlin#423]
**Describe the bug 🐛**
When I perform a search using `searchSingleIndex` with `SearchParamsObject`, the call throws an exception with the following stacktrace:
```
com.algolia.client.exception.AlgoliaClientException: Illegal input: Failed to deserialize json element: "Overnight pudink s chia a ovesnými vločkami"
2024-08-19 15:27:02.285 30426-30426 at com.algolia.client.exception.internal.ThrowableKt.asClientException(Throwable.kt:10)
2024-08-19 15:27:02.286 30426-30426 at com.algolia.client.transport.internal.KtorRequester.onError(KtorRequester.kt:99)
2024-08-19 15:27:02.286 30426-30426 at com.algolia.client.transport.internal.KtorRequester.execute(KtorRequester.kt:64)
2024-08-19 15:27:02.286 30426-30426 at com.algolia.client.transport.internal.KtorRequester$execute$1.invokeSuspend(Unknown Source:15)
2024-08-19 15:27:02.287 30426-30426 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-08-19 15:27:02.287 30426-30426 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
2024-08-19 15:27:02.287 30426-30426 at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
2024-08-19 15:27:02.288 30426-30426 at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
2024-08-19 15:27:02.289 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:149)
2024-08-19 15:27:02.289 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:134)
2024-08-19 15:27:02.290 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:89)
2024-08-19 15:27:02.290 30426-30426 at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:177)
2024-08-19 15:27:02.290 30426-30426 at io.ktor.client.HttpClient$4.invoke(Unknown Source:11)
2024-08-19 15:27:02.290 30426-30426 at io.ktor.client.HttpClient$4.invoke(Unknown Source:6)
2024-08-19 15:27:02.291 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:131)
2024-08-19 15:27:02.291 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:89)
2024-08-19 15:27:02.291 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:99)
2024-08-19 15:27:02.291 30426-30426 at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142)
2024-08-19 15:27:02.292 30426-30426 at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:13)
2024-08-19 15:27:02.292 30426-30426 at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:6)
2024-08-19 15:27:02.292 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:131)
2024-08-19 15:27:02.292 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:89)
2024-08-19 15:27:02.292 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:109)
2024-08-19 15:27:02.293 30426-30426 at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
2024-08-19 15:27:02.293 30426-30426 at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:89)
2024-08-19 15:27:02.293 30426-30426 at io.ktor.client.call.HttpClientCallKt.body(HttpClientCall.kt:165)
2024-08-19 15:27:02.294 30426-30426 at com.algolia.client.transport.internal.KtorRequester.execute(KtorRequester.kt:60)
2024-08-19 15:27:02.294 30426-30426 at com.algolia.client.transport.internal.KtorRequester$execute$1.invokeSuspend(Unknown Source:15)
2024-08-19 15:27:02.294 30426-30426 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-08-19 15:27:02.295 30426-30426 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-08-19 15:27:02.295 30426-30426 at android.os.Handler.handleCallback(Handler.java:942)
2024-08-19 15:27:02.295 30426-30426 at android.os.Handler.dispatchMessage(Handler.java:99)
2024-08-19 15:27:02.296 30426-30426 at android.os.Looper.loopOnce(Looper.java:201)
2024-08-19 15:27:02.296 30426-30426 at android.os.Looper.loop(Looper.java:288)
2024-08-19 15:27:02.297 30426-30426 at android.app.ActivityThread.main(ActivityThread.java:7872)
2024-08-19 15:27:02.297 30426-30426 at java.lang.reflect.Method.invoke(Native Method)
2024-08-19 15:27:02.297 30426-30426 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2024-08-19 15:27:02.297 30426-30426 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2024-08-19 15:27:02.298 30426-30426 ed by: io.ktor.serialization.JsonConvertException: Illegal input: Failed to deserialize json element: "Overnight pudink s chia a ovesnými vločkami"
2024-08-19 15:27:02.298 30426-30426 at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:90)
2024-08-19 15:27:02.299 30426-30426 at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:224)
2024-08-19 15:27:02.299 30426-30426 at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:114)
2024-08-19 15:27:02.300 30426-30426 at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:113)
2024-08-19 15:27:02.300 30426-30426 at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:239)
2024-08-19 15:27:02.300 30426-30426 at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source:1)
2024-08-19 15:27:02.301 30426-30426 at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:123)
2024-08-19 15:27:02.301 30426-30426 at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertResponse$ktor_client_content_negotiation(ContentNegotiation.kt:232)
2024-08-19 15:27:02.301 30426-30426 at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:264)
2024-08-19 15:27:02.301 30426-30426 at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:13)
2024-08-19 15:27:02.302 30426-30426 at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:6)
2024-08-19 15:27:02.302 30426-30426 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:131)
2024-08-19 15:27:02.302 30426-30426 ... 28 more
2024-08-19 15:27:02.303 30426-30426 ed by: com.algolia.client.exception.AlgoliaClientException: Failed to deserialize json element: "Overnight pudink s chia a ovesnými vločkami"
2024-08-19 15:27:02.303 30426-30426 at com.algolia.client.model.search.HighlightResultSerializer.selectDeserializer(HighlightResult.kt:57)
2024-08-19 15:27:02.304 30426-30426 at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:93)
2024-08-19 15:27:02.304 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.304 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
2024-08-19 15:27:02.305 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement$lambda$1(Tagged.kt:279)
2024-08-19 15:27:02.305 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.$r8$lambda$DBYIndnlKB76_oyt-Ap4f_T35nM(Unknown Source:0)
2024-08-19 15:27:02.305 30426-30426 at kotlinx.serialization.internal.TaggedDecoder$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
2024-08-19 15:27:02.306 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
2024-08-19 15:27:02.306 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
2024-08-19 15:27:02.306 30426-30426 at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
2024-08-19 15:27:02.307 30426-30426 at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
2024-08-19 15:27:02.307 30426-30426 at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
2024-08-19 15:27:02.307 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
2024-08-19 15:27:02.307 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
2024-08-19 15:27:02.308 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
2024-08-19 15:27:02.308 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.308 30426-30426 at com.algolia.client.model.search.HighlightResult$MapOfkotlinStringHighlightResultValue$$serializer.deserialize-uSYLPVs(HighlightResult.kt:24)
2024-08-19 15:27:02.309 30426-30426 at com.algolia.client.model.search.HighlightResult$MapOfkotlinStringHighlightResultValue$$serializer.deserialize(HighlightResult.kt:24)
2024-08-19 15:27:02.309 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.309 30426-30426 at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:26)
2024-08-19 15:27:02.309 30426-30426 at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:186)
2024-08-19 15:27:02.309 30426-30426 at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:94)
2024-08-19 15:27:02.310 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.310 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
2024-08-19 15:27:02.310 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement$lambda$1(Tagged.kt:279)
2024-08-19 15:27:02.311 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.$r8$lambda$DBYIndnlKB76_oyt-Ap4f_T35nM(Unknown Source:0)
2024-08-19 15:27:02.311 30426-30426 at kotlinx.serialization.internal.TaggedDecoder$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
2024-08-19 15:27:02.312 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
2024-08-19 15:27:02.312 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
2024-08-19 15:27:02.312 30426-30426 at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
2024-08-19 15:27:02.312 30426-30426 at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
2024-08-19 15:27:02.313 30426-30426 at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
2024-08-19 15:27:02.313 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
2024-08-19 15:27:02.313 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
2024-08-19 15:27:02.314 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
2024-08-19 15:27:02.315 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.315 30426-30426 at com.algolia.client.model.search.HighlightResult$MapOfkotlinStringHighlightResultValue$$serializer.deserialize-uSYLPVs(HighlightResult.kt:24)
2024-08-19 15:27:02.315 30426-30426 at com.algolia.client.model.search.HighlightResult$MapOfkotlinStringHighlightResultValue$$serializer.deserialize(HighlightResult.kt:24)
2024-08-19 15:27:02.315 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.316 30426-30426 at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:26)
2024-08-19 15:27:02.316 30426-30426 at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:186)
2024-08-19 15:27:02.316 30426-30426 at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:94)
2024-08-19 15:27:02.317 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.317 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
2024-08-19 15:27:02.317 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement$lambda$1(Tagged.kt:279)
2024-08-19 15:27:02.317 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.$r8$lambda$DBYIndnlKB76_oyt-Ap4f_T35nM(Unknown Source:0)
2024-08-19 15:27:02.318 30426-30426 at kotlinx.serialization.internal.TaggedDecoder$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
2024-08-19 15:27:02.318 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
2024-08-19 15:27:02.318 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
2024-08-19 15:27:02.319 30426-30426 at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
2024-08-19 15:27:02.319 30426-30426 at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
2024-08-19 15:27:02.319 30426-30426 at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
2024-08-19 15:27:02.320 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
2024-08-19 15:27:02.320 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
2024-08-19 15:27:02.320 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
2024-08-19 15:27:02.321 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.321 30426-30426 at kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
2024-08-19 15:27:02.321 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.321 30426-30426 at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:26)
2024-08-19 15:27:02.321 30426-30426 at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:186)
2024-08-19 15:27:02.321 30426-30426 at com.algolia.client.model.search.HitSerializer.deserialize(Hit.kt:77)
2024-08-19 15:27:02.322 30426-30426 at com.algolia.client.model.search.HitSerializer.deserialize(Hit.kt:38)
2024-08-19 15:27:02.323 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.323 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
2024-08-19 15:27:02.324 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement$lambda$1(Tagged.kt:279)
2024-08-19 15:27:02.324 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.$r8$lambda$DBYIndnlKB76_oyt-Ap4f_T35nM(Unknown Source:0)
2024-08-19 15:27:02.324 30426-30426 at kotlinx.serialization.internal.TaggedDecoder$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
2024-08-19 15:27:02.324 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
2024-08-19 15:27:02.324 30426-30426 at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
2024-08-19 15:27:02.325 30426-30426 at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
2024-08-19 15:27:02.325 30426-30426 at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
2024-08-19 15:27:02.326 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
2024-08-19 15:27:02.326 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
2024-08-19 15:27:02.327 30426-30426 at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
2024-08-19 15:27:02.327 30426-30426 at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
2024-08-19 15:27:02.327 30426-30426 at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:26)
2024-08-19 15:27:02.328 30426-30426 at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:186)
2024-08-19 15:27:02.328 30426-30426 at com.algolia.client.model.search.SearchResponseSerializer.deserialize(SearchResponse.kt:265)
2024-08-19 15:27:02.328 30426-30426 at com.algolia.client.model.search.SearchResponseSerializer.deserialize(SearchResponse.kt:144)
2024-08-19 15:27:02.329 30426-30426 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
2024-08-19 15:27:02.330 30426-30426 at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
2024-08-19 15:27:02.330 30426-30426 at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:82)
```

I briefly debugged and it seems that the root cause is that `HighlightResultSerializer.selectDeserializer` doesn't support  a case when the `element` is `JsonLiteral`.

https://github.com/algolia/algoliasearch-client-kotlin/blob/c7435f815fed6cb72bf39646f1cb08bcfe037bb3/client/src/commonMain/kotlin/com/algolia/client/model/search/HighlightResult.kt#L50-L59

**OS**: Android API 33
**Version**: algoliasearch-client-kotlin 3.0.0

**Comment by shortcuts** [comment]
Hey, I think the fix we are currently releasing might solve this issue too, I'll let you know once 3.0.2 (there's a version skip due to a release error) is released!

**Comment by lenoch0d** [comment]
Alright, thanks for the heads up!

**Comment by lenoch0d** [comment]
The error still occurs in 3.0.2

**Comment by shortcuts** [comment]
> The error still occurs in 3.0.2

Would you mind sharing an example of the response you receive, if you manage to make the same API call via a curl command for example? Or your appID, the search query and the indexName?

Having such reproduction would allow me to run e2e tests on every clients to try to spot the issue

**Comment by lenoch0d** [comment]
The `_highlightResults` field in the JSON from the API response looks like this: 
```
"_highlightResult": {
      "title": {
          "cs": {
              "value": "Losos s dušenou zeleninou",
              "matchLevel": "none",
              "matchedWords": []
          },
          "da": {
              "value": "Laks med dampet grøntsager",
              "matchLevel": "none",
              "matchedWords": []
          }
   }
}
```

I can reproduce it consistently, with any query. AppID is `97eot9yol6`, index `recipes`

**Comment by shortcuts** [comment]
Hey, a fix should be available in the next version later today!

**Comment by shortcuts** [comment]
Wonderful, enjoy!
