### ISSUE TITLE
[bug]: When using SearchSingleIndex, passing offset & length still requires the key 'page'

### ISSUE THREAD

**Issue by andrasfecz** [algolia/algoliasearch-client-kotlin#425]
### Description

When passing offset and length as parameters into searchSingleIndex getting an error about 'page' missing. Page should not be required if using offset & length.

Happens with:
implementation "com.algolia:algoliasearch-client-kotlin:3.3.0"

### Client

Search

### Version

3.3.0

### Relevant log output

```shell
com.algolia.client.exception.AlgoliaClientException: Illegal input: Key page is missing in the map.
	at com.algolia.client.exception.internal.ThrowableKt.asClientException(Throwable.kt:10)
	at com.algolia.client.transport.internal.KtorRequester.onError(KtorRequester.kt:109)
	at com.algolia.client.transport.internal.KtorRequester.execute(KtorRequester.kt:74)
	at com.algolia.client.transport.internal.KtorRequester$execute$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
Caused by: io.ktor.serialization.JsonConvertException: Illegal input: Key page is missing in the map.
```

**Comment by Fluf22** [comment]
Hey! 👋🏻 
Thank you very much for the report. I managed to reproduce, I'm looking into it
